---
# Configure paths & directories, checkout PHPEnv
- name: Setup Build Environment
  import_tasks: setup.yml

- name: Install Phpenv & PHP
  import_tasks: install.yml

- name: Copy Nginx Config
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/php-{{ domain }}.conf
  become: yes
  when: domain is defined
  notify: Restart Nginx

- name: Install Composer & Dependencies
  import_tasks: composer.yml

- name: Copy phpinfo.php
  copy: src=phpinfo.php dest={{ http_root }}/{{ domain }}/public/phpinfo.php
  when: copy_phpinfo

- name: Copy index.php
  template: src=index.php.j2 dest={{ http_root }}/{{ domain }}/public/index.php
  when: copy_index_php

- name: Set Local PHP Version
  copy: content={{ php_version }} dest={{ http_root }}/{{ domain }}/.php-version
  when: domain is defined
