---
- name: Install Git
  apt: name=git state=present
  become: yes

- name: Create Phpenv Directory
  file:
    path: "{{ phpenv_root }}"
    state: directory
    owner: root
    group: web-admin
    mode: 02775
  become: yes

- name: Allow Web Admins to Write Phpenv Directory
  acl:
    name: "{{ phpenv_root }}"
    etype: group
    entity: web-admin
    permissions: rwx
    state: present
  become: yes

- name: Allow Web Admins Write to Future Directories in Phpenv
  acl:
    name: "{{ phpenv_root }}"
    etype: group
    entity: web-admin
    permissions: rwx
    default: yes
    state: present
  become: yes

- name: Set ACL Mask for Phpenv
  acl:
    name: "{{ phpenv_root }}"
    etype: mask
    permissions: rwx
    default: yes
    state: present
  become: yes

- name: Install Phpenv
  git:
    repo: https://github.com/phpenv/phpenv.git
    dest: "{{ phpenv_root }}"
    version: "{{ phpenv_version }}"
    update: no

- name: Install PHP-Build Plugin
  git:
    repo: https://github.com/bbatsche/php-build.git
    dest: "{{ phpenv_root }}/plugins/php-build"
    version: "{{ php_build_version }}"
    update: no

- name: Install Phpenv Composer Plugin
  git:
    repo: https://github.com/bbatsche/phpenv-composer.git
    dest: "{{ phpenv_root }}/plugins/phpenv-composer"
    version: "{{ phpenv_composer_version }}"
    update: no
  notify: Rehash Phpenv

- name: Add Phpenv to Profile
  template: src=phpenv.sh.j2 dest=/etc/profile.d/phpenv.sh mode=0755
  become: yes

- name: Add Tempfiles Config
  lineinfile:
    dest: /etc/tmpfiles.d/phpenv.conf
    state: present
    line: d /tmp/phpenv/{{ item.path }} {{ item.mode }} www-data web-admin 1w
    regexp: "^d /tmp/phpenv/{{ item.path }} "
    create: yes
  become: yes
  when: ansible_distribution_release != "trusty"
  register: tempfile_result
  loop:
    - { path: "{{ php_version }}",               mode: "02775" }
    - { path: "{{ php_version }}/opcache",       mode: "02770" }

- name: Add Domain to Tempfiles
  lineinfile:
    dest: /etc/tmpfiles.d/phpenv.conf
    state: present
    line: d /tmp/phpenv/{{ php_version }}/{{ domain }} 02770 www-data web-admin 1w
    create: yes
  become: yes
  register: domain_tempfile_result
  when:
    - domain is defined
    - ansible_distribution_release != "trusty"
